StudentInformationSystemWebApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentInformationSystemWebApp.Models;

namespace StudentInformationSystemWebApp.Controllers
{
    public class StudentController : Controller
    {
        private ApplicationDbContext _context;

        public StudentController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        //
        // GET: /Student/
        [HttpGet]
        public ActionResult Save()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Save(Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Students.Add(student);
                int rowEffect = _context.SaveChanges();
                if (rowEffect > 0)
                {
                    ViewBag.Messege = "Save Successful";
                    ModelState.Clear();
                }
                else ViewBag.Messege = "Save Failed!";
            }
            else
            {
                ViewBag.Messege = "Model State Invalid";
            }
            return View();
        }
	}
}

StudentInformationSystemWebApp/Controllers/StudentCourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StudentInformationSystemWebApp.Models;

namespace StudentInformationSystemWebApp.Controllers
{
    public class StudentCourseController : Controller
    {
        private ApplicationDbContext _context;

        public StudentCourseController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        //
        // GET: /StudentCourse/
        [HttpGet]
        public ActionResult Save()
        {
            var studentList = _context.Students.ToList();
            var courseList = _context.Courses.ToList();
            var semesterList = new List<Semester>
            {
                new Semester() {Name = "Spring", Code = "SP"},
                new Semester() {Name = "Summer", Code = "SU"},
                new Semester() {Name = "Fall", Code = "FA"}
            };
            var viewModel = new StudentCourseViewModel()
            {
                StudentList = studentList,
                CourseList = courseList,
                SemesterList = semesterList
            };

            return View(viewModel);
        }
	}
}

StudentInformationSystemWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Student Information System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Student Information System", "Save", "Student", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Student", "Save", "Student")</li>
                    <li>@Html.ActionLink("Course", "Save", "Course")</li>
                    <li>@Html.ActionLink("Student't Course", "Save", "StudentCourse")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Student Information System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>